version: '2.1'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    networks:
      - local
    healthcheck:
      test: sleep 1; mysql -h127.0.0.1 -P3306 -uroot -p${MYSQL_ROOT_PASSWORD} -e'select 1;'
      interval: 20s
      timeout: 19s
      retries: 60
networks:
  local:
    external:
      name: local
